export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const VERIFY = 'VERIFY';
export const GET_INFORMATION_TRANSACTION = 'GET_INFORMATION_TRANSACTION';
export const GET_INFORMATION_TRANSACTION_ERROR = 'GET_INFORMATION_TRANSACTION_ERROR';
export const POST_INFORMATION_TRANSACTION = 'POST_INFORMATION_TRANSACTION_ERROR';
export const POST_INFORMATION_TRANSACTION_ERROR = 'POST_INFORMATION_TRANSACTION_ERROR';
export const SWITCH_MOVED = 'SWITCH_MOVED';
export const SWITCH_VERIFY = 'SWITCH_VERIFY';
export const DELETE_CONFIRMINFO = 'DELETE_CONFIRMINFO';
export const POST_VERIFY_TRANSACTION = 'POST_VERIFY_TRANSACTION';
export const POST_VERIFY_TRANSACTION_ERROR = 'POST_VERIFY_TRANSACTION_ERROR';
export const GET_LIST_TRANSACTION = "GET_LIST_TRANSACTION";
// account
export const GET_ACCOUNT = "GET_ACCOUNT";

//   saving account

export const FETCH_SAVING_ACCOUNT = "FETCH_SAVING_ACCOUNT";
export const FETCH_SAVING_ACCOUNT_ERROR = "FETCH_SAVING_ACCOUNT_ERROR";
export const GET_SAVING_DETAIL = "GET_SAVING_DETAIL";
export const ON_FINALIZATION = "ON_FINALIZATION";
export const POST_VERIFY_FINALIZATION = 'POST_VERIFY_FINALIZATION';

// add saving account
export const POST_INFORMATION_ADD_SAING = 'POST_INFORMATION_ADD_SAING';
export const SWITCH_MOVED_ADD_SAVING = 'SWITCH_MOVED_ADD_SAVING';
export const POST_VERIFY_ADD_SAVING = 'POST_VERIFY_ADD_SAVING';
export const SWITCH_VERIFY_ADD_SAVING = 'SWITCH_VERIFY_ADD_SAVING';
export const DELETE_CONFIRMINFO_ADD_SAVING = 'DELETE_CONFIRMINFO_ADD_SAVING';


//profile


// Login

export const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";
export const POST_LOGIN = "POST_LOGIN";
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_STATE_USER = "RESET_STATE_USER";
export const REFRESH_USER ="REFRESH_USER";

//change password
export const POST_CHECK_TOKEN = "POST_CHECK_TOKEN";
export const POST_CHANGE_PASSWORD = "POST_CHANGE_PASSWORD";

//register
export const POST_REGISTER = "POST_REGISTER";

//verify image
export const POST_VERIFY_IMAGE ="POST_VERIFY_IMAGE";


///----------- ADMIN ---------------

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_PENDING = "GET_ALL_USER_PENDING";
export const RESET_ADMIN = "RESET_ADMIN";
//detail user
export const GET_USER_TRANSACTION = "GET_USER_TRANSACTION";
export const ADD_USER_AMOUNT = "ADD_USER_AMOUNT";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";
export const LOCK_USER = "LOCK_USER";
export const ACCEPT_USER = "ACCEPT_USER";
export const DENY_USER = "ACCEPT_USER";
 





